//eslint-disable-next-line no-unused-vars
/*global systemDictionary:true */

"use strict";

systemDictionary = {
  "withings adapter settings": {
    en: "Adapter settings for withings",
    de: "Adaptereinstellungen für withings",
    ru: "Настройки адаптера для withings",
    pt: "Configurações do adaptador para withings",
    nl: "Adapterinstellingen voor withings",
    fr: "Paramètres d'adaptateur pour withings",
    it: "Impostazioni dell'adattatore per withings",
    es: "Ajustes del adaptador para withings",
    pl: "Ustawienia adaptera dla withings",
    "zh-cn": "withings的适配器设置",
  },
  "App Email": {
    en: "App Email",
    de: "App-E-Mail",
    ru: "Электронная почта приложения",
    pt: "Email do aplicativo",
    nl: "App-e-mail",
    fr: "Courriel de l'application",
    it: "E-mail dell'app",
    es: "Correo electrónico de la aplicación",
    pl: "E-mail aplikacji",
    "zh-cn": "应用电子邮件",
  },
  "App Password": {
    en: "App Password",
    de: "App-Passwort",
    ru: "Пароль приложения",
    pt: "Senha de app",
    nl: "App-wachtwoord",
    fr: "Mot de passe de l'application",
    it: "Password dell'app",
    es: "Contraseña de la aplicación",
    pl: "Hasło do aplikacji",
    "zh-cn": "应用密码",
  },
  "Update interval (in minutes)": {
    en: "Update interval (in minutes)",
    de: "Aktualisierungsintervall (in Minuten)",
    ru: "Интервал обновления (в минутах)",
    pt: "Intervalo de atualização (em minutos)",
    nl: "Update-interval (in minuten)",
    fr: "Intervalle de mise à jour (en minutes)",
    it: "Intervallo di aggiornamento (in minuti)",
    es: "Intervalo de actualización (en minutos)",
    pl: "Interwał aktualizacji (w minutach)",
    "zh-cn": "更新间隔（分钟）",
  },
  "Client Secret": {
    en: "Client Secret",
    de: "Consumer-Geheimnis",
    ru: "Секрет клиента",
    pt: "Segredo do cliente",
    nl: "Klantgeheim",
    fr: "Secret du client",
    it: "Segreto del cliente",
    es: "Secreto del cliente",
    pl: "Sekret klienta",
    "zh-cn": "客户机密",
  },
  "Please open the link and register": {
    en: "Please open the link and register",
    de: "Bitte Link öffnen und registrieren",
    ru: "Пожалуйста, откройте ссылку и зарегистрируйтесь",
    pt: "Por favor, abra o link e registre-se",
    nl: "Open de link en schrijf je in",
    fr: "Veuillez ouvrir le lien et vous inscrire",
    it: "Si prega di aprire il link e registrarsi",
    es: "Por favor abra el enlace y regístrese.",
    pl: "Otwórz link i zarejestruj się",
    "zh-cn": "请打开链接并注册",
  },
  "Restricted Mode: Yes": {
    en: "Restricted Mode: Yes",
    de: "Eingeschränkter Modus: Ja",
    ru: "Ограниченный режим: Да",
    pt: "Modo restrito: Sim",
    nl: "Beperkte modus: Ja",
    fr: "Mode restreint : Oui",
    it: "Modalità con restrizioni: Sì",
    es: "Modo restringido: sí",
    pl: "Tryb ograniczonego dostępu: tak",
    "zh-cn": "受限模式：是",
  },
  "Fetch last x days": {
    en: "Fetch last x days",
    de: "Letzte x Tage abrufen",
    ru: "Получить за последние x дней",
    pt: "Buscar últimos x dias",
    nl: "Laatste x dagen ophalen",
    fr: "Récupérer les x derniers jours",
    it: "Recupera gli ultimi x giorni",
    es: "Obtener los últimos x días",
    pl: "Pobierz ostatnie x dni",
    "zh-cn": "获取最近 x 天",
  },
  "Fetch last x hours for sleep": {
    en: "Fetch last x hours for sleep",
    de: "Letzte x Stunden zum Schlafen abrufen",
    ru: "Получить последние x часов для сна",
    pt: "Buscar últimas x horas para dormir",
    nl: "Laatste x uur halen om te slapen",
    fr: "Récupérer les x dernières heures pour dormir",
    it: "Recupera le ultime x ore per dormire",
    es: "Obtener las últimas x horas para dormir",
    pl: "Pobierz ostatnie x godzin snu",
    "zh-cn": "获取最后 x 小时的睡眠时间",
  },
};
